language: java

install: true

before_install:
    - openssl aes-256-cbc -K $encrypted_f76c010fc1af_key -iv $encrypted_f76c010fc1af_iv -in .travis/ssh-key.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/id_rsa
    - cp .travis/ssh_config ~/.ssh/config
    - chmod +x .travis/deploysf.sh
    - echo $PUBKEY > ~/.ssh/id_rsa.pub
    - ls -a ~/.ssh
    - sudo apt-get update
    - sudo apt-get install openssh-client zip
    
before_deploy:
- echo $projectversion
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$projectversion-B$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Development build $TRAVIS_BUILD_NUMBER from Travis-CI"
- git push -q https://$GITPERM@github.com/mob41/KmbETA-API --tags
- ls -l

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITPERM
  file: 
    - KmbETA-API-$projectversion-$TRAVIS_BRANCH-B$TRAVIS_BUILD_NUMBER.zip
  on:
    tags: false
    branch: develop

after_success:
    - mvn package
    - cd target
    - ls -l
    - zip KmbETA-API-$projectversion-$TRAVIS_BRANCH-B$TRAVIS_BUILD_NUMBER.zip KmbETA-API-$projectversion.jar KmbETA-API-$projectversion-jar-with-dependencies.jar KmbETA-API-$projectversion-javadoc.jar
    - if [ "$TRAVIS_BRANCH" = "master" ]; then ../.travis/deploysf.sh ; fi
      
branches:
    only:
        - master
        - develop
      
env:
- projectversion=1.0.0-SNAPSHOT