language: java

install: true

before_deploy:
- echo $projectversion
- mvn package
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$projectversion-B$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GITPERM@github.com/mob41/KmbETA-API --tags
- ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITPERM
  file: 
    - target/KmbETA-API-$projectversion.jar
    - target/KmbETA-API-$projectversion-jar-with-dependencies.jar
    - target/KmbETA-API-$projectversion-javadoc.jar
  on:
    tags: false
    branch: master

env:
- projectversion=1.0.0-SNAPSHOT